# Workflow name
name: Deploy to Heroku

# Run workflow on every push to main branch
on:
  push:
    branches: [main]

# Workflow jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Build, push, and release Docker container to Heroku
      - name: Build, Push and Release Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
          heroku_cli: true   # Ensures Heroku CLI is available for release
