on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # 3. Login to Heroku Container Registry
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      # 4. Build and push Docker image
      - name: Build and push Docker image
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          docker build \
            --file ./Dockerfile \
            --tag registry.heroku.com/$HEROKU_APP_NAME/web \
            --no-cache \
            ./
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      # 5. Set Heroku stack to container
      - name: Set Heroku stack to container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku stack:set container --app $HEROKU_APP_NAME

      # 6. Release Docker container
      - name: Release Docker container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          # Release the newly pushed image
          heroku container:release web --app $HEROKU_APP_NAME